<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="onebill-Latitude-3410" ignored="0" name="Amazon Login for Invalid PhoneNumber" tests="1" failures="1" timestamp="23 Aug 2021 14:00:01 GMT" time="4.851" errors="0">
  <testcase name="adhoc1" time="2.275" classname="com.amazon.watch.NegativeScenario3Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [We cannot find an account with that mobile number] but found [We cannot find an account with that mobile 888number]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [We cannot find an account with that mobile number] but found [We cannot find an account with that mobile 888number]
at com.amazon.watch.NegativeScenario3Test.adhoc1(NegativeScenario3Test.java:35)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- adhoc1 -->
</testsuite> <!-- Amazon Login for Invalid PhoneNumber -->
